---
- hosts: 127.0.0.1
  vars:
    ansible_python_interpreter: /usr/bin/python3
   
  tasks:
    - name: List all files and directories in ~
      shell: ls ~
      register: dir_contents
    - name: Print directory contents using loops
      debug:
        msg: "{{ item }}"
      loop: "{{ dir_contents.stdout_lines }}"
