---
- hosts: mygroup
  vars:
    package_names:
      - nano
      - telnet
  tasks:
    - name: "Check if vim package is installed or not on Debian Linux family"
      package:
        name: "{{ item }}"
        state: present
      check_mode: true
      loop: "{{ package_names }}"
      register: package_check

    - name: "Print execution results"
      debug:
        msg: "Package is installed"
      when: package_check is succeeded      
