---
- hosts: mygroup
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
  - name: "install nano"
    apt:
      name: nano
      state: latest
      
  vars:
    ansible_python_interpreter: /usr/bin/python3
